<!DOCTYPE HTML>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="estilo_2.css">
    <title>Alvo</title>
  </head>
    <body>
               <div id="red_bar">
                <nav id="nav_principal">
                    <div id="nav_p_logo">
                        Alvo
                    </div>
                    <div id="nav_p_itens">
                        <ul>
                            <li><a href="#">O</a></li>
                            <li><a>X</a></li>
                            <li><a>@</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
         <div id="geral">
            <nav id="sidebar">
                <ul>
                    <div id="sidebar_block">
                      <li><a href="#">Perfil</a></li>
                    </div>
                    <div id="sidebar_block">
                      <li><a href="#">Mensagem</a></li>
                    </div>
                    <div id="sidebar_block">
                      <li><a href="#">Projetos</a></li>
                        <ul class="inside">
                          <li>Projeto 1</li>
                          <li>Projeto 2</li>
                          <li class="projeto_ativo">Projeto 3</li>
                        </ul>
                    </div>
                </ul>
            </nav>
        </div>
    </body>
    </html>