
<div class="row">
    <div class="col-xs-12">
        <h1>Submissão de Documentos</h1>

        <form enctype="multipart/form-data" action="<?php echo $this->url(array('controller' => 'SubmitDocs', 'action' => 'upload')) ?>" method="POST">

            <input type="hidden" name="fk_id_projeto" value="<?php echo $this->idproj; ?>"/>

            <div class="form-group">
                <span>Nome do arquivo:</span>                    
                <input class="form-control" type="text" name="nome"/>
            </div>
            <div class="form-group">
                <span>Arquivo:</span>   
                <input class="form-control" name="upload" type="file" />
            </div>
            <button class="">Enviar</button>
        </form>
    </div>

    <div class="col-xs-12" >
        <div class="1" style="padding: 10px !important;border: 1;">
            <?php
            if ($this->docs != null) {
                foreach ($this->docs as $tupla) {
                    ?>

                    <div class="col-xs-2">

                        <div>
                            <a href="http://localhost/alvo/public/uploads/<?php echo $tupla['titulo_documento']; ?>"> 
                                <div class="tile" style="margin:5px;padding:0px;">
                                    <i class="tile-image glyphicon glyphicon-file" style="font-size:65px;margin-bottom:0;"></i>
                                    <h4 class="tile-title"></h4>
                                    <p style="overflow-wrap: normal;"><?php echo $tupla['titulo_documento']; ?></p>
                                </div>
                            </a>
                        </div>
                    </div>
                    <?php
                }
            }
            ?>
</div>
    </div>
    
   