<!DOCTYPE html>
<html>
    <head>
        <title><?php echo $this->titulo ?></title>
    </head>
    <body>
        <h1>Inserção</h1>
        <form action="<?php echo $this->url(array('controller' => 'Mensagem', 'action' => 'form')); ?>" method="post">
            <input type="text" name="destinatario" placeholder="destinatario">
            <input type="hidden" name="fk_id_projeto" value="<?php echo $this->idproj; ?>"/>
            <textarea name="mensagem" placeholder="mensagem"></textarea>
            <input type="submit" value="Gravar">
        </form>
        <a href="<?php echo $this->url(array('controller' => 'Index', 'action' => 'index')); ?>">Voltar</a>

        <h6><?php echo $this->warning; ?></h6>
    </body>
</html>