<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>ALVO</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Loading Bootstrap -->

        <link href="http://localhost/alvo/public/css/flat-ui.css" rel="stylesheet">
        <link href="http://localhost/alvo/public/bootstrap/css/bootstrap.css" rel="stylesheet">
        <link href="http://localhost/alvo/public/bootstrap/css/prettify.css" rel="stylesheet">
        

        <script src="http://localhost/alvo/public/js/jquery-1.8.3.min.js"></script>
      
        <script src="http://localhost/alvo/public/js/jquery-ui-1.10.3.custom.min.js"></script>
        <script src="http://localhost/alvo/public/js/jquery.ui.touch-punch.min.js"></script>
        <script src="http://localhost/alvo/public/js/bootstrap.min.js"></script>
        <script src="http://localhost/alvo/public/js/bootstrap-select.js"></script>
        <script src="http://localhost/alvo/public/js/bootstrap-switch.js"></script>
        <script src="http://localhost/alvo/public/js/flatui-checkbox.js"></script>
        <script src="http://localhost/alvo/public/js/flatui-radio.js"></script>
        <script src="http://localhost/alvo/public/js/jquery.tagsinput.js"></script>
        <script src="http://localhost/alvo/public/js/jquery.placeholder.js"></script>
        <script src="http://localhost/alvo/public/js/typeahead.js"></script>
        <script src="http://localhost/alvo/public/bootstrap/js/google-code-prettify/prettify.js"></script>
        <script src="http://localhost/alvo/public/js/application.js"></script>


    </head>