<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>ALVO</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="http://localhost/alvo/public/js/jquery-1.8.3.min.js"></script>
        <script src="http://localhost/alvo/public/js/login.js"></script>

        <link href="http://localhost/alvo/public/bootstrap/css/estilo_1.css" rel="stylesheet">


    </head>
